package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMessage<M extends BaseMessage<M>> extends Model<M> implements IBean {

	public void setMessageId(java.lang.Integer messageId) {
		set("messageId", messageId);
	}
	
	public java.lang.Integer getMessageId() {
		return getInt("messageId");
	}

	public void setReceiveId(java.lang.Integer receiveId) {
		set("receiveId", receiveId);
	}
	
	public java.lang.Integer getReceiveId() {
		return getInt("receiveId");
	}

	public void setSendId(java.lang.Integer sendId) {
		set("sendId", sendId);
	}
	
	public java.lang.Integer getSendId() {
		return getInt("sendId");
	}

	public void setText(java.lang.String text) {
		set("text", text);
	}
	
	public java.lang.String getText() {
		return getStr("text");
	}

	public void setSendTime(java.util.Date sendTime) {
		set("sendTime", sendTime);
	}
	
	public java.util.Date getSendTime() {
		return get("sendTime");
	}

	public void setReadFlag(java.lang.Boolean readFlag) {
		set("readFlag", readFlag);
	}
	
	public java.lang.Boolean getReadFlag() {
		return get("readFlag");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setTaskId(java.lang.Integer taskId) {
		set("taskId", taskId);
	}
	
	public java.lang.Integer getTaskId() {
		return getInt("taskId");
	}

}
