package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	public void setCreditId(java.lang.Integer creditId) {
		set("creditId", creditId);
	}
	
	public java.lang.Integer getCreditId() {
		return getInt("creditId");
	}

	public void setWechatId(java.lang.String wechatId) {
		set("wechatId", wechatId);
	}
	
	public java.lang.String getWechatId() {
		return getStr("wechatId");
	}

	public void setIntroduction(java.lang.String introduction) {
		set("introduction", introduction);
	}
	
	public java.lang.String getIntroduction() {
		return getStr("introduction");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public void setIdentity(java.lang.Boolean identity) {
		set("identity", identity);
	}
	
	public java.lang.Boolean getIdentity() {
		return get("identity");
	}

	public void setRegisterTime(java.util.Date registerTime) {
		set("registerTime", registerTime);
	}
	
	public java.util.Date getRegisterTime() {
		return get("registerTime");
	}

	public void setAdvantage(java.lang.String advantage) {
		set("advantage", advantage);
	}
	
	public java.lang.String getAdvantage() {
		return getStr("advantage");
	}

	public void setMail(java.lang.String mail) {
		set("mail", mail);
	}
	
	public java.lang.String getMail() {
		return getStr("mail");
	}

}
