package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProject<M extends BaseProject<M>> extends Model<M> implements IBean {

	public void setProjectId(java.lang.Integer projectId) {
		set("projectId", projectId);
	}
	
	public java.lang.Integer getProjectId() {
		return getInt("projectId");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setOverTime(java.util.Date overTime) {
		set("overTime", overTime);
	}
	
	public java.util.Date getOverTime() {
		return get("overTime");
	}

	public void setCreatorId(java.lang.Integer creatorId) {
		set("creatorId", creatorId);
	}
	
	public java.lang.Integer getCreatorId() {
		return getInt("creatorId");
	}

	public void setProjectContents(java.lang.String projectContents) {
		set("projectContents", projectContents);
	}
	
	public java.lang.String getProjectContents() {
		return getStr("projectContents");
	}

	public void setProjectRequire(java.lang.String projectRequire) {
		set("projectRequire", projectRequire);
	}
	
	public java.lang.String getProjectRequire() {
		return getStr("projectRequire");
	}

}
