package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJudge<M extends BaseJudge<M>> extends Model<M> implements IBean {

	public void setJudgeid(java.lang.Integer judgeid) {
		set("judgeid", judgeid);
	}
	
	public java.lang.Integer getJudgeid() {
		return getInt("judgeid");
	}

	public void setUserid(java.lang.Integer userid) {
		set("userid", userid);
	}
	
	public java.lang.Integer getUserid() {
		return getInt("userid");
	}

	public void setIsfinish(java.lang.Boolean isfinish) {
		set("isfinish", isfinish);
	}
	
	public java.lang.Boolean getIsfinish() {
		return get("isfinish");
	}

}
