package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTask<M extends BaseTask<M>> extends Model<M> implements IBean {

	public void setTaskId(java.lang.Integer taskId) {
		set("taskId", taskId);
	}
	
	public java.lang.Integer getTaskId() {
		return getInt("taskId");
	}

	public void setProjectId(java.lang.Integer projectId) {
		set("projectId", projectId);
	}
	
	public java.lang.Integer getProjectId() {
		return getInt("projectId");
	}

	public void setCreatorId(java.lang.Integer creatorId) {
		set("creatorId", creatorId);
	}
	
	public java.lang.Integer getCreatorId() {
		return getInt("creatorId");
	}

	public void setProjectContent(java.lang.String projectContent) {
		set("projectContent", projectContent);
	}
	
	public java.lang.String getProjectContent() {
		return getStr("projectContent");
	}

	public void setParentProjectId(java.lang.Integer parentProjectId) {
		set("parentProjectId", parentProjectId);
	}
	
	public java.lang.Integer getParentProjectId() {
		return getInt("parentProjectId");
	}

	public void setPjRequirement(java.lang.String pjRequirement) {
		set("pjRequirement", pjRequirement);
	}
	
	public java.lang.String getPjRequirement() {
		return getStr("pjRequirement");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setOverTime(java.util.Date overTime) {
		set("overTime", overTime);
	}
	
	public java.util.Date getOverTime() {
		return get("overTime");
	}

	public void setIsEmpty(java.lang.Boolean isEmpty) {
		set("isEmpty", isEmpty);
	}
	
	public java.lang.Boolean getIsEmpty() {
		return get("isEmpty");
	}

	public void setWeight(java.lang.String weight) {
		set("weight", weight);
	}
	
	public java.lang.String getWeight() {
		return getStr("weight");
	}

	public void setProjectflag(java.lang.Integer projectflag) {
		set("projectflag", projectflag);
	}
	
	public java.lang.Integer getProjectflag() {
		return getInt("projectflag");
	}

	public void setPeople(java.lang.Integer people) {
		set("people", people);
	}
	
	public java.lang.Integer getPeople() {
		return getInt("people");
	}

	public void setCurrentPeople(java.lang.Integer currentPeople) {
		set("currentPeople", currentPeople);
	}
	
	public java.lang.Integer getCurrentPeople() {
		return getInt("currentPeople");
	}

	public void setFinishFlag(java.lang.Boolean finishFlag) {
		set("finishFlag", finishFlag);
	}
	
	public java.lang.Boolean getFinishFlag() {
		return get("finishFlag");
	}

}
