package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCredit<M extends BaseCredit<M>> extends Model<M> implements IBean {

	public void setCreditId(java.lang.Integer creditId) {
		set("creditId", creditId);
	}
	
	public java.lang.Integer getCreditId() {
		return getInt("creditId");
	}

	public void setFailure(java.lang.Integer failure) {
		set("failure", failure);
	}
	
	public java.lang.Integer getFailure() {
		return getInt("failure");
	}

	public void setSuccess(java.lang.Integer success) {
		set("success", success);
	}
	
	public java.lang.Integer getSuccess() {
		return getInt("success");
	}

	public void setCreditScore(java.lang.Integer creditScore) {
		set("creditScore", creditScore);
	}
	
	public java.lang.Integer getCreditScore() {
		return getInt("creditScore");
	}

	public void setPraise(java.lang.Integer praise) {
		set("praise", praise);
	}
	
	public java.lang.Integer getPraise() {
		return getInt("praise");
	}

	public void setBad(java.lang.Integer bad) {
		set("bad", bad);
	}
	
	public java.lang.Integer getBad() {
		return getInt("bad");
	}

	public void setMid(java.lang.Integer mid) {
		set("mid", mid);
	}
	
	public java.lang.Integer getMid() {
		return getInt("mid");
	}

}
