package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJoins<M extends BaseJoins<M>> extends Model<M> implements IBean {

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	public void setTaskId(java.lang.Integer taskId) {
		set("taskId", taskId);
	}
	
	public java.lang.Integer getTaskId() {
		return getInt("taskId");
	}

	public void setJoinId(java.lang.Integer joinId) {
		set("joinId", joinId);
	}
	
	public java.lang.Integer getJoinId() {
		return getInt("joinId");
	}

	public void setJoinTime(java.util.Date joinTime) {
		set("joinTime", joinTime);
	}
	
	public java.util.Date getJoinTime() {
		return get("joinTime");
	}

	public void setIsFinish(java.lang.Boolean isFinish) {
		set("isFinish", isFinish);
	}
	
	public java.lang.Boolean getIsFinish() {
		return get("isFinish");
	}

}
