package com.demo.common.model;

import com.demo.common.model.base.BaseCollection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Collection extends BaseCollection<Collection> {
	
}
